# Default style file for nitpick
# https://raw.githubusercontent.com/andreoliwa/nitpick/v0.22.2/nitpick-style.toml

[nitpick]
minimum_version = "0.23.1"

[nitpick.styles]
include = [
    "nitpick-style-base",
    "styles/license-apache2",
]

[nitpick.files."setup.cfg"]
comma_separated_values = ["flake8.ignore", "flake8.exclude"]
