["pyproject.toml".tool.black]
line-length = 120
target-version = ["py39"]

[["pre-commit-config.yaml".repos]]
yaml = """
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.11.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==21.9b0]
"""