["pyproject.toml".tool.isort]
profile="black"
line_length = 120

[["pre-commit-config.yaml".repos]]
yaml = """
  - repo: https://github.com/timothycrosley/isort
    rev: 5.9.3
    hooks:
      - id: isort
"""
