# [["requirements/base.txt".contains]]
# line = "fastapi~=0.92.0"

# [["requirements/base.txt".contains]]
# line = "uvloop==0.17.0"

# [["requirements/base.txt".contains]]
# line = "hypercorn==0.14.3"
